config/routes.rb
Rails.application.routes.draw do

  # 会員側
  devise_for :users, controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
  }

  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員側
  scope module: :member do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :comics, only: [:index, :show] do
      resources :comic_bookshelves, only: [:create, :destroy]
      resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    end
    
    resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy]
    
    resources :bookshelves, only: [:index, :show, :destroy]
    
    get "/users/information/edit" => "users#edit", as: "edit_user"
    get "/users/my_page" => "users#show", as: "user"
    patch "/users/information" => "users#update", as: "update_user"
    get "/users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
    patch "/users/withdraw" => "users#withdraw", as: "withdraw"

  end

  # 管理者側
  namespace :admin do
    root to: "homes#top", as: "top"

    resources :comics, only: [:new, :create, :show, :edit, :update, :destroy]
    
    resources :bookshelves, only: [:index, :show, :destroy]

    resources :genres, only: [:index, :create, :edit, :update, :destroy]

    resources :users, only: [:edit, :show, :update, :destroy]

    resources :reviews, only: [:index, :show, :destroy]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookshelf.rb
class Bookshelf < ApplicationRecord
  
  # belongs_to :user
  # has_many :comic_bookshelves
  # has_many :comics, through: :comic_bookshelves
  
  belongs_to :user
  belongs_to :comic

  def user_count
    comic_bookshelves.joins(:user).distinct.count(:user_id)
  end
end

app/models/comic.rb
class Comic < ApplicationRecord

  belongs_to :genre
  # has_many :comic_bookshelves
  # has_many :bookshelves, through: :comic_bookshelves
  has_many :reviews, dependent: :destroy
  has_many :bookshelves
  has_many :users, through: :bookshelves
  
  has_one_attached :image
  
  validates :genre_id, presence: { message: "ジャンルを選択してください" }
  validates :title, presence: { message: "タイトルを入力してください" }
  validates :volume, presence: { message: "既巻数を入力してください" }, numericality: { only_integer: true, greater_than: 0 }
  validates :next_date, presence: { message: "次巻発売日を入力してください" }
  
  def image_with_default
    image.attached? ? image : Rails.root.join("app/assets/images/no_image.jpg")
  end
  
  def bookshelf_by?(user)
    bookshelf.exists?(user_id: user.id)
  end
  
end

app/models/comic_bookshelf.rb
class ComicBookshelf < ApplicationRecord

  belongs_to :comic
  belongs_to :bookshelf

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :comics
  
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :comic, optional: true
  belongs_to :user

  validates :body, presence: { message: "感想を入力してください。" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # has_many :comic_bookshelves  
  # has_many :bookshelves, through: :comic_bookshelves, source: :comic
  has_many :reviews, dependent: :destroy
  
  has_many :bookshelves
  has_many :comics, through: :bookshelves
  
  validates :nickname, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]{2,})\z/i }
  
  def has_comic_in_bookshelf?(comic)
    bookshelves.exists?(comic_id: comic.id)
  end
  
end 

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @params = params[:id]
    @comics = Comic.page(params[:page]).per(10)
    @comics = Comic.all
    # タイトル検索
    if params[:title].present?
      @comics = @comics.where('title LIKE ?', "%#{params[:title]}%")
    end
    # ジャンル検索
    if params[:genre_id].present?
      @comics = @comics.where(genre_id: params[:genre_id])
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/member/homes_controller.rb
class Member::HomesController < ApplicationController
  
  def top
  end 
  
end

app/helpers/admin/bookshelves_helper.rb
module Admin::BookshelvesHelper
end

app/helpers/admin/comics_helper.rb
module Admin::ComicsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member/bookshelves_helper.rb
module Member::BookshelvesHelper
end

app/helpers/member/comics_helper.rb
module Member::ComicsHelper
end

app/helpers/member/genres_helper.rb
module Member::GenresHelper
end

app/helpers/member/homes_helper.rb
module Member::HomesHelper
end

app/helpers/member/posts_helper.rb
module Member::PostsHelper
end

app/helpers/member/users_helper.rb
module Member::UsersHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-5">
    <div class="col-5 text-center border-bottom">
      <h4 class="px-4">漫画一覧</h4>
    </div>
  </div>
  
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-6 mx-auto">
      <%= form_with(url: admin_top_path, method: :get, local: true, class: "form-inline") do %>
        <%= text_field_tag :title, params[:title], placeholder: "タイトルで検索", class: "form-control mr-2" %>
        <%= select_tag :genre_id, options_from_collection_for_select(Genre.all, :id, :name, selected: params[:genre_id]), include_blank: "ジャンルを選択", class: "form-control mr-2" %>
        <%= submit_tag "検索", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="row mt-5">
    <% if @comics.empty? %>
      <p>該当する漫画は見つかりませんでした。</p>
    <% else %>
      <% @comics.each do |comic| %>
        <div class="col-12 col-md-4 col-lg-3">
          <div class="card mb-4" style="max-width: 260px;">
            <div class="card-img-top" style="height: 200px; background-color: #f8f9fa;">
            <%= image_tag comic.image.attached? ? comic.image : 'no_image.jpg', class: 'img-fluid', style: 'width: 100%; height: 100%; object-fit: contain;' %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to comic.title, admin_comic_path(comic) %></h5>
              <p class="card-title">ジャンル : <%= comic.genre.name %></p>
              <p class="card-title">発売中 : <%= comic.volume %>巻</p>
              <p class="card-title">次巻発売日 : <%= comic.next_date.strftime("%Y年%m月%d日") %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>