config/routes.rb
Rails.application.routes.draw do

  # 会員側
  devise_for :users, controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
  }

  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員側
  scope module: :member do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :comics, only: [:index, :show] do
      resources :comic_bookshelves, only: [:create, :destroy]
      resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    end
    
    resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy]
    
    resources :bookshelves, only: [:index, :show, :destroy]
    
    get "/users/information/edit" => "users#edit", as: "edit_user"
    get "/users/my_page" => "users#show", as: "user"
    patch "/users/information" => "users#update", as: "update_user"
    get "/users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
    patch "/users/withdraw" => "users#withdraw", as: "withdraw"

  end

  # 管理者側
  namespace :admin do
    root to: "homes#top", as: "top"

    resources :comics, only: [:new, :create, :show, :edit, :update, :destroy]
    
    resources :bookshelves, only: [:index, :show, :destroy]

    resources :genres, only: [:index, :create, :edit, :update, :destroy]

    resources :users, only: [:edit, :show, :update, :destroy]

    resources :reviews, only: [:index, :show, :destroy]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookshelf.rb
class Bookshelf < ApplicationRecord
  
  # belongs_to :user
  # has_many :comic_bookshelves
  # has_many :comics, through: :comic_bookshelves
  
  belongs_to :user
  belongs_to :comic

  def user_count
    comic_bookshelves.joins(:user).distinct.count(:user_id)
  end
end

app/models/comic.rb
class Comic < ApplicationRecord

  belongs_to :genre
  # has_many :comic_bookshelves
  # has_many :bookshelves, through: :comic_bookshelves
  has_many :reviews, dependent: :destroy
  has_many :bookshelves
  has_many :users, through: :bookshelves
  
  has_one_attached :image
  
  validates :genre_id, presence: { message: "ジャンルを選択してください" }
  validates :title, presence: { message: "タイトルを入力してください" }
  validates :volume, presence: { message: "既巻数を入力してください" }, numericality: { only_integer: true, greater_than: 0 }
  validates :next_date, presence: { message: "次巻発売日を入力してください" }
  
  def image_with_default
    image.attached? ? image : Rails.root.join("app/assets/images/no_image.jpg")
  end
  
  def bookshelf_by?(user)
    bookshelf.exists?(user_id: user.id)
  end
  
end

app/models/comic_bookshelf.rb
class ComicBookshelf < ApplicationRecord

  belongs_to :comic
  belongs_to :bookshelf

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :comics
  
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :comic, optional: true
  belongs_to :user

  validates :body, presence: { message: "感想を入力してください。" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # has_many :comic_bookshelves  
  # has_many :bookshelves, through: :comic_bookshelves, source: :comic
  has_many :reviews, dependent: :destroy
  
  has_many :bookshelves
  has_many :comics, through: :bookshelves
  
  validates :nickname, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]{2,})\z/i }
  
  def has_comic_in_bookshelf?(comic)
    bookshelves.exists?(comic_id: comic.id)
  end
  
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comics_helper.rb
module Admin::ComicsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member/comics_helper.rb
module Member::ComicsHelper
end

app/helpers/member/genres_helper.rb
module Member::GenresHelper
end

app/helpers/member/homes_helper.rb
module Member::HomesHelper
end

app/helpers/member/posts_helper.rb
module Member::PostsHelper
end

app/helpers/member/users_helper.rb
module Member::UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件のエラー") %>が発生したため保存されませんでした。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row justify-content-md-center pt-3" style="height:75px;">
    
    <div class="col-auto">
      <%= link_to "管理者ログイン", admin_top_path %>
    </div>
    
  </div>
</div>

app/views/layouts/_header_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-light justify-content-center" style ="background-color:#f8f8ff;">
  <div class="container">
    <a class="navbar-brand" href="/"><%= image_tag "Mycomics_2.png", size: "150x80" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to new_admin_comic_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ff7f50">漫画新規登録</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_top_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#00bfff">漫画一覧</button>
            <% end %>
          </li>
          
          <li class="nav-item">
            <%= link_to admin_genres_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ccff99">ジャンル一覧</button>
            <% end %>
          </li>
          
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ffd700">ログアウト</button>
            <% end %>
          </li>
        <% else %>

          <li class="nav-item ">
            <%= link_to comics_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#00bfff">漫画一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ffd700">ログイン</button>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header_member.html.erb
<nav class="navbar navbar-expand-lg navbar-light justify-content-center" style ="background-color:#f8f8ff;">
  <div class="container">
    <a class="navbar-brand" href="/"><%= image_tag "Mycomics_2.png", size: "150x80" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ff7f50">マイページ</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to comics_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#00bfff">漫画一覧</button>
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to bookshelves_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ccff99">本棚<i class="fa-sharp-duotone fa-solid fa-books"></i></button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ffd700">ログアウト</button>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item ">
            <%= link_to comics_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#00bfff">漫画一覧</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ccff99">新規登録</button>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link text-dark text-right" do %>
              <button class="btn" style="background-color:#ffd700">ログイン</button>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mycomics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/b57b19ae52.js" crossorigin="anonymous"></script>
  </head>
  
  
  <body class="d-flex flex-column vh-100">
    <header class="border-bottom" style ="background-color:#f8f8ff;">
      <% if admin_signed_in? %>
        <%= render 'layouts/header_admin' %>
      <% else %>
        <%= render 'layouts/header_member' %>
      <% end %>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="border-top" style ="background-color:#f8f8ff;">
      <%= render 'layouts/footer' %>
    </footer>
  </body>

</html>