config/routes.rb
Rails.application.routes.draw do

  # 会員側
  devise_for :users, controllers: {
    registrations: "member/registrations",
    sessions: 'member/sessions'
  }

  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 会員側
  scope module: :member do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :comics, only: [:index, :show] do
      resources :comic_bookshelves, only: [:create, :destroy]
      resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    end
    
    resources :reviews, only: [:index, :show, :create, :edit, :update, :destroy]
    
    resources :bookshelves, only: [:index, :show, :destroy]
    
    get "/users/information/edit" => "users#edit", as: "edit_user"
    get "/users/my_page" => "users#show", as: "user"
    patch "/users/information" => "users#update", as: "update_user"
    get "/users/unsubscribe" => "users#unsubscribe", as: "unsubscribe"
    patch "/users/withdraw" => "users#withdraw", as: "withdraw"

  end

  # 管理者側
  namespace :admin do
    root to: "homes#top", as: "top"

    resources :comics, only: [:new, :create, :show, :edit, :update, :destroy]
    
    resources :bookshelves, only: [:index, :show, :destroy]

    resources :genres, only: [:index, :create, :edit, :update, :destroy]

    resources :users, only: [:edit, :show, :update, :destroy]

    resources :reviews, only: [:index, :show, :destroy]

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookshelf.rb
class Bookshelf < ApplicationRecord
  
  # belongs_to :user
  # has_many :comic_bookshelves
  # has_many :comics, through: :comic_bookshelves
  
  belongs_to :user
  belongs_to :comic

  def user_count
    comic_bookshelves.joins(:user).distinct.count(:user_id)
  end
end

app/models/comic.rb
class Comic < ApplicationRecord

  belongs_to :genre
  # has_many :comic_bookshelves
  # has_many :bookshelves, through: :comic_bookshelves
  has_many :reviews, dependent: :destroy
  has_many :bookshelves
  has_many :users, through: :bookshelves
  
  has_one_attached :image
  
  validates :genre_id, presence: { message: "ジャンルを選択してください" }
  validates :title, presence: { message: "タイトルを入力してください" }
  validates :volume, presence: { message: "既巻数を入力してください" }, numericality: { only_integer: true, greater_than: 0 }
  validates :next_date, presence: { message: "次巻発売日を入力してください" }
  
  def image_with_default
    image.attached? ? image : Rails.root.join("app/assets/images/no_image.jpg")
  end
  
  def bookshelf_by?(user)
    bookshelf.exists?(user_id: user.id)
  end
  
end

app/models/comic_bookshelf.rb
class ComicBookshelf < ApplicationRecord

  belongs_to :comic
  belongs_to :bookshelf

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :comics
  
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :comic, optional: true
  belongs_to :user

  validates :body, presence: { message: "感想を入力してください。" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # has_many :comic_bookshelves  
  # has_many :bookshelves, through: :comic_bookshelves, source: :comic
  has_many :reviews, dependent: :destroy
  
  has_many :bookshelves
  has_many :comics, through: :bookshelves
  
  validates :nickname, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]{2,})\z/i }
  
  def has_comic_in_bookshelf?(comic)
    bookshelves.exists?(comic_id: comic.id)
  end
  
end 

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_comic, only: [:show, :edit, :update, :destroy]

  def new
    @comic = Comic.new
    @genres = Genre.all
  end

  def create
    @comic = Comic.new(comic_params)
    @genres = Genre.all
    if @comic.save
      flash[:comic_new] = "漫画が正常に登録されました。"
      redirect_to admin_top_path
    else
      flash.now[:comic_alert] = "漫画の登録に失敗しました。"
      render :new
    end
  end

  def show
    @bookshelves = @comic.bookshelves
    @user_count = @bookshelves.count
    @comic = Comic.find(params[:id])
    @reviews = @comic.reviews.includes(:user).order(created_at: :desc)
  end

  def edit
    @genres = Genre.all
  end

  def update
    if @comic.update(comic_params)
      flash[:comic_show] = "漫画情報が更新されました。"
      redirect_to admin_comic_path(@comic)
    else
      flash.now[:comic_alert] = "漫画情報の更新に失敗しました。"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comic.destroy
    flash[:comic_] = "漫画が削除されました。"
    redirect_to admin_comics_path
  end

  private
  
  def set_comic
    @comic = Comic.find(params[:id])
  end

  def comic_params
    params.require(:comic).permit(:genre_id, :title, :volume, :next_date, :image)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @params = params[:id]
    @comics = Comic.page(params[:page]).per(10)
    @comics = Comic.all
    # タイトル検索
    if params[:title].present?
      @comics = @comics.where('title LIKE ?', "%#{params[:title]}%")
    end
    # ジャンル検索
    if params[:genre_id].present?
      @comics = @comics.where(genre_id: params[:genre_id])
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/member/comics_controller.rb
class Member::ComicsController < ApplicationController
  
  def index
    @comics = Comic.all
    # タイトル検索
    if params[:title].present?
      @comics = @comics.where('title LIKE ?', "%#{params[:title]}%")
    end
    # ジャンル検索
    if params[:genre_id].present?
      @comics = @comics.where(genre_id: params[:genre_id])
    end
  end
  
  def show
    @comic = Comic.find(params[:id])
    @reviews = @comic.reviews.includes(:user).order(created_at: :desc)
  end 
  
  def add_to_bookshelf
    @comic = Comic.find(params[:comic_id])
    if current_user.bookshelves.find_or_create_by(comic: @comic)
      flash[:notice] = "漫画を本棚に追加しました。"
    end
    redirect_to comics_path
  end

  def remove_from_bookshelf
    @comic = Comic.find(params[:comic_id])
    if (bookshelf = current_user.bookshelves.find_by(comic: @comic))
      bookshelf.destroy
      flash[:notice] = '漫画を本棚から削除しました。'
    end
    redirect_back fallback_location: comics_path
  end
  
end

app/helpers/admin/bookshelves_helper.rb
module Admin::BookshelvesHelper
end

app/helpers/admin/comics_helper.rb
module Admin::ComicsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member/bookshelves_helper.rb
module Member::BookshelvesHelper
end

app/helpers/member/comics_helper.rb
module Member::ComicsHelper
end

app/helpers/member/genres_helper.rb
module Member::GenresHelper
end

app/helpers/member/homes_helper.rb
module Member::HomesHelper
end

app/helpers/member/posts_helper.rb
module Member::PostsHelper
end

app/helpers/member/users_helper.rb
module Member::UsersHelper
end

app/views/admin/comics/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-5">
    <div class="col-5 text-center border-bottom">
      <h4 class="px-4">漫画詳細編集</h4>
    </div>
  </div>
  
  <%= form_with(model: @comic, url: admin_comic_path(@comic), method: :PATCH) do |f| %>

    <div class="row justify-content-md-center mt-5">
      <div class="col-3 text-right">画像</div>
      <div class="col-3">
        <%= f.file_field :image %>
      </div>
    </div>
    
    <div class="row justify-content-md-center mt-5">
      <div class="col-3 text-right">漫画タイトル</div>
      <div class="col-3">
        <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "漫画タイトル" %>
      </div>
    </div>
    
    <div class="row justify-content-md-center mt-5">
      <div class="col-3 text-right">ジャンル</div>
      <div class="col-3">
        <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "-- 選択してください --" %>
      </div>
    </div>
    
    <div class="row justify-content-md-center mt-5">
      <div class="col-3 text-right">既巻数</div>
      <div class="col-3">
        <%= f.text_field :volume, autofocus: true, autocomplete: "volume", placeholder: "既巻数" %>
      </div>
    </div>
    
    <div class="row justify-content-md-center mt-5">
      <div class="col-3 text-right">次巻発売日</div>
      <div class="col-3">
        <%= f.date_field :next_date, autofocus: true, autocomplete: "next_date", placeholder: "次巻発売日" %>
      </div>
    </div>
    
    <div class = "row justify-content-md-center my-3">
      <div class="col-lg-3 text-center">
       <%= f.submit "保存する", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/comics/new.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-5">
    <div class="col-5 text-center border-bottom">
      <h4 class="px-4">漫画新規登録</h4>
    </div>
  </div>
  
  <div class = "row justify-content-md-center text-success mt-3"><%= flash[:comic_alert] %></div>
  
  <%= form_with model: @comic, url: admin_comics_path, method: :post do |f| %>
    
    <div class="row justify-content-md-center my-5">
      <div class="col-3 text-right">画像</div>
      <div class="col-3">
        <%= f.file_field :image %>
      </div>
    </div>
    
    <div class="row justify-content-md-center my-5">
      <div class="col-3 text-right">漫画タイトル</div>
      <div class="col-3">
        <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "漫画タイトル" %>
      </div>
    </div>
    
    <div class="row justify-content-md-center my-5">
      <div class="col-3 text-right">ジャンル</div>
      <div class="col-3">
        <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "-- 選択してください --" %>
      </div>
    </div>
    
    <div class="row justify-content-md-center my-5">
      <div class="col-3 text-right">最新巻</div>
      <div class="col-3">
        <%= f.text_field :volume, autofocus: true, autocomplete: "volume", placeholder: "既巻数" %>
      </div>
    </div>
    
    <div class="row justify-content-md-center my-5">
      <div class="col-3 text-right">次巻発売日</div>
      <div class="col-3">
        <%= f.date_field :next_date, autofocus: true, autocomplete: "next_date", placeholder: "次巻発売日" %>
      </div>
    </div>
    
    <div class="row justify-content-md-center mb-5">
      <div class="col-auto">
        <%= f.submit "漫画新規登録", class: "col btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/comics/show.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-5">
    <div class="col-5 text-center border-bottom">
      <h4 class="px-4">漫画詳細</h4>
    </div>
  </div>

  <div class = "row justify-content-md-center text-success mt-3"><%= flash[:user_show] %></div>
  <div class="row justify-content-center mt-5">
    <div class="col-12 text-center">
      <%= image_tag @comic.image.attached? ? @comic.image : "no_image.jpg", class: "img-fluid", style: "max-width: 260px;" %>
    </div>
    <div class="col-6 mt-3">
      <table class="table table-bordered text-center">
        <tr>
          <th class="col-5 table-info">漫画タイトル</th>
          <td><%= @comic.title %></td>
        </tr>
        <tr>
          <th class="table-info">本棚追加ユーザー人数</th>
          <td><%= @user_count %></td>
        </tr>
        <tr>
          <th class="table-info">ジャンル</th>
          <td><%= @comic.genre.name %></td>
        </tr>
        <tr>
          <th class="table-info">最新巻</th>
          <td><%= @comic.volume %>巻</td>
        </tr>
        <tr>
          <th class="table-info">次巻発売日</th>
          <td><%= @comic.next_date.strftime("%Y年%m月%d日") %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class = "row justify-content-center my-5">
    <div class="col-auto">
      <%= link_to "編集する", edit_admin_comic_path, class: "btn btn-success" %>
    </div>
  </div>
  <div class="row justify-content-md-center mt-5">
    <div class="col-7 text-center border-bottom">
      <h4 class="px-4">レビュー一覧</h4>
    </div>
  </div>
    <% if @reviews.any? %>
      <% @reviews.each do |review| %>
        <div class="review mt-3 p-3 border rounded">
          <p><strong><%= review.user.nickname %></strong>（投稿日: <%= review.created_at.strftime("%Y年%m月%d日") %>）</p>
          <p><%= review.body %></p>
        </div>
      <% end %>
    <% else %>
      <p>まだレビューが投稿されていません。</p>
    <% end %>
  
</div>